# Generated by Django 3.0 on 2020-10-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
